<?php

namespace AppBundle\Entity;

/**
 * AdditionalProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdditionalProductRepository extends \Doctrine\ORM\EntityRepository {

    public function findAllBoardingsOrderedByPositionInList() { // returns array of AdditionalProduct objects
        return $this->getEntityManager()
                        ->createQuery("
                SELECT 
                
                ap
                
                FROM AppBundle:AdditionalProduct ap
                JOIN ap.additionalproductcategory apc
                WHERE apc.identifier = 'boardings'
		
		ORDER BY ap.positionInList ASC
                "
                        )
                        ->getResult();
    }

    public function findAllSpecialsOrderedByPositionInList() { // returns array of AdditionalProduct objects
        return $this->getEntityManager()
                        ->createQuery("
                SELECT 
                
                ap
                
                FROM AppBundle:AdditionalProduct ap
                JOIN ap.additionalproductcategory apc
                WHERE apc.identifier = 'specials'
		
		ORDER BY ap.positionInList ASC
                "
                        )
                        ->getResult();
    }

}
