<?php

namespace AppBundle\Entity;

/**
 * AdditionalProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdditionalProductRepository extends \Doctrine\ORM\EntityRepository
{
}
