<?php

namespace AppBundle\Entity;

/**
 * AvailabilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvailabilityRepository extends \Doctrine\ORM\EntityRepository {

    public function findAvailability(CheckInOutDateTime $ciodt, RoomType $rt) { // returns integer
        $result = $this->getEntityManager()
                ->createQuery("
                SELECT 
                
                MIN(av.quantity)
                
                FROM AppBundle:Availability av
                JOIN av.roomType rt
                
                WHERE rt.identifier = ?1
                AND av.date >= ?2
                AND av.date < ?3
                "
                )->setParameters(array(
                    1 => $rt->getIdentifier(),
                    2 => $ciodt->getCheckInDateTime(),
                    3 => $ciodt->getCheckOutDateTime()
                        )
                )
                ->getSingleScalarResult();
        if (!$result) {
            return intval($rt->getCapacity());
        }
        return intval($result);
    }

}
