<?php

namespace AppBundle\Entity;

/**
 * HotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelRepository extends \Doctrine\ORM\EntityRepository
{
     public function getEmailAddress () { // returns String

        $em = $this->getEntityManager();

        $query = $em->createQuery(
                'SELECT h FROM AppBundle:hotel h'
        );
        
        $result = $query->getResult(); // Array of Hotel Objects

        return $result[0]->getEmail(); 
    }
    
}
