<?php

namespace AppBundle\Entity;

/**
 * RoomTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
